name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
    - run: buildah build --tag=docker.io/fwilhe2/dev toolbox-image
    - name: Log into DockerHub
      run: echo "${{ secrets.DH_PAT }}" | buildah docker.io login -u fwilhe2 --password-stdin
    - name: Push image
      run: buildah push docker.io/fwilhe2/dev
